[package]
name = "sonik"
version = "0.1.0"
authors = ["adcrn <9167686+adcrn@users.noreply.github.com>"]
edition = "2018"

[dependencies]
tui = "0.5"
termion = "1.5"
failure = "*"
rand = "0.6.5"
walkdir = "2"
rodio = "*"
rusqlite = "*"
id3 = "*"
dirs = "*"
app_dirs2 = "*"
serde_derive = "*"
serde = "*"
toml = "*"
ignore = "*"

[dependencies.cursive]
version = "*"
default-features = false
features = ["termion-backend"]
